name: Build and Push to ECR - Modulo de Catalogos

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "aws_session_token=${AWS_SESSION_TOKEN}" >> ~/.aws/credentials

      - name: Build and push Docker image
        env:
          ECR_URI: ${{ secrets.ECR_URI_CATALOGO }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          docker build --build-arg DB_HOST=$DB_HOST \
                       --build-arg DB_USER=$DB_USER \
                       --build-arg DB_PASSWORD=$DB_PASSWORD \
                       --build-arg DB_NAME=$DB_NAME \
                       -t catalogos:latest .
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin $ECR_URI
          docker tag catalogos:latest $ECR_URI:catalogos
          docker push $ECR_URI:catalogos